// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: pricing.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PriceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Odometer      int32                  `protobuf:"varint,2,opt,name=odometer,proto3" json:"odometer,omitempty"`
	Grade         int32                  `protobuf:"varint,3,opt,name=grade,proto3" json:"grade,omitempty"`
	ExteriorColor string                 `protobuf:"bytes,4,opt,name=exterior_color,json=exteriorColor,proto3" json:"exterior_color,omitempty"`
	InteriorColor string                 `protobuf:"bytes,5,opt,name=interior_color,json=interiorColor,proto3" json:"interior_color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceRequest) Reset() {
	*x = PriceRequest{}
	mi := &file_pricing_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceRequest) ProtoMessage() {}

func (x *PriceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceRequest.ProtoReflect.Descriptor instead.
func (*PriceRequest) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{0}
}

func (x *PriceRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *PriceRequest) GetOdometer() int32 {
	if x != nil {
		return x.Odometer
	}
	return 0
}

func (x *PriceRequest) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

func (x *PriceRequest) GetExteriorColor() string {
	if x != nil {
		return x.ExteriorColor
	}
	return ""
}

func (x *PriceRequest) GetInteriorColor() string {
	if x != nil {
		return x.InteriorColor
	}
	return ""
}

type PriceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         uint64                 `protobuf:"varint,1,opt,name=price,proto3" json:"price,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PriceResponse) Reset() {
	*x = PriceResponse{}
	mi := &file_pricing_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PriceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PriceResponse) ProtoMessage() {}

func (x *PriceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pricing_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PriceResponse.ProtoReflect.Descriptor instead.
func (*PriceResponse) Descriptor() ([]byte, []int) {
	return file_pricing_proto_rawDescGZIP(), []int{1}
}

func (x *PriceResponse) GetPrice() uint64 {
	if x != nil {
		return x.Price
	}
	return 0
}

var File_pricing_proto protoreflect.FileDescriptor

const file_pricing_proto_rawDesc = "" +
	"\n" +
	"\rpricing.proto\x12\apricing\x1a\x1cgoogle/api/annotations.proto\"\xa0\x01\n" +
	"\fPriceRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x1a\n" +
	"\bodometer\x18\x02 \x01(\x05R\bodometer\x12\x14\n" +
	"\x05grade\x18\x03 \x01(\x05R\x05grade\x12%\n" +
	"\x0eexterior_color\x18\x04 \x01(\tR\rexteriorColor\x12%\n" +
	"\x0einterior_color\x18\x05 \x01(\tR\rinteriorColor\"%\n" +
	"\rPriceResponse\x12\x14\n" +
	"\x05price\x18\x01 \x01(\x04R\x05price2\x81\x01\n" +
	"\x0ePricingService\x12o\n" +
	"\x13GetRecommendedPrice\x12\x15.pricing.PriceRequest\x1a\x16.pricing.PriceResponse\")\x82\xd3\xe4\x93\x02#:\x01*\"\x1e/pricing/get-recommended-priceBjZhgithub.com/alechekz/online-car-auction-clean-archv2/services/pricing/internal/transport/grpc/proto;protob\x06proto3"

var (
	file_pricing_proto_rawDescOnce sync.Once
	file_pricing_proto_rawDescData []byte
)

func file_pricing_proto_rawDescGZIP() []byte {
	file_pricing_proto_rawDescOnce.Do(func() {
		file_pricing_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)))
	})
	return file_pricing_proto_rawDescData
}

var file_pricing_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pricing_proto_goTypes = []any{
	(*PriceRequest)(nil),  // 0: pricing.PriceRequest
	(*PriceResponse)(nil), // 1: pricing.PriceResponse
}
var file_pricing_proto_depIdxs = []int32{
	0, // 0: pricing.PricingService.GetRecommendedPrice:input_type -> pricing.PriceRequest
	1, // 1: pricing.PricingService.GetRecommendedPrice:output_type -> pricing.PriceResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pricing_proto_init() }
func file_pricing_proto_init() {
	if File_pricing_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pricing_proto_rawDesc), len(file_pricing_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pricing_proto_goTypes,
		DependencyIndexes: file_pricing_proto_depIdxs,
		MessageInfos:      file_pricing_proto_msgTypes,
	}.Build()
	File_pricing_proto = out.File
	file_pricing_proto_goTypes = nil
	file_pricing_proto_depIdxs = nil
}
