// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: inspection.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetBuildDataRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBuildDataRequest) Reset() {
	*x = GetBuildDataRequest{}
	mi := &file_inspection_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBuildDataRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBuildDataRequest) ProtoMessage() {}

func (x *GetBuildDataRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspection_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBuildDataRequest.ProtoReflect.Descriptor instead.
func (*GetBuildDataRequest) Descriptor() ([]byte, []int) {
	return file_inspection_proto_rawDescGZIP(), []int{0}
}

func (x *GetBuildDataRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

type BuildDataResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Brand         string                 `protobuf:"bytes,2,opt,name=brand,proto3" json:"brand,omitempty"`
	Engine        string                 `protobuf:"bytes,3,opt,name=engine,proto3" json:"engine,omitempty"`
	Transmission  string                 `protobuf:"bytes,4,opt,name=transmission,proto3" json:"transmission,omitempty"`
	Msrp          uint64                 `protobuf:"varint,5,opt,name=msrp,proto3" json:"msrp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BuildDataResponse) Reset() {
	*x = BuildDataResponse{}
	mi := &file_inspection_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BuildDataResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuildDataResponse) ProtoMessage() {}

func (x *BuildDataResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inspection_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuildDataResponse.ProtoReflect.Descriptor instead.
func (*BuildDataResponse) Descriptor() ([]byte, []int) {
	return file_inspection_proto_rawDescGZIP(), []int{1}
}

func (x *BuildDataResponse) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *BuildDataResponse) GetBrand() string {
	if x != nil {
		return x.Brand
	}
	return ""
}

func (x *BuildDataResponse) GetEngine() string {
	if x != nil {
		return x.Engine
	}
	return ""
}

func (x *BuildDataResponse) GetTransmission() string {
	if x != nil {
		return x.Transmission
	}
	return ""
}

func (x *BuildDataResponse) GetMsrp() uint64 {
	if x != nil {
		return x.Msrp
	}
	return 0
}

type InspectVehicleRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Vin             string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Year            int32                  `protobuf:"varint,2,opt,name=year,proto3" json:"year,omitempty"`
	Odometer        int32                  `protobuf:"varint,3,opt,name=odometer,proto3" json:"odometer,omitempty"`
	SmallScratches  bool                   `protobuf:"varint,4,opt,name=small_scratches,json=smallScratches,proto3" json:"small_scratches,omitempty"`
	StrongScratches bool                   `protobuf:"varint,5,opt,name=strong_scratches,json=strongScratches,proto3" json:"strong_scratches,omitempty"`
	ElectricFail    bool                   `protobuf:"varint,6,opt,name=electric_fail,json=electricFail,proto3" json:"electric_fail,omitempty"`
	SuspensionFail  bool                   `protobuf:"varint,7,opt,name=suspension_fail,json=suspensionFail,proto3" json:"suspension_fail,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *InspectVehicleRequest) Reset() {
	*x = InspectVehicleRequest{}
	mi := &file_inspection_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectVehicleRequest) ProtoMessage() {}

func (x *InspectVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_inspection_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectVehicleRequest.ProtoReflect.Descriptor instead.
func (*InspectVehicleRequest) Descriptor() ([]byte, []int) {
	return file_inspection_proto_rawDescGZIP(), []int{2}
}

func (x *InspectVehicleRequest) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *InspectVehicleRequest) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

func (x *InspectVehicleRequest) GetOdometer() int32 {
	if x != nil {
		return x.Odometer
	}
	return 0
}

func (x *InspectVehicleRequest) GetSmallScratches() bool {
	if x != nil {
		return x.SmallScratches
	}
	return false
}

func (x *InspectVehicleRequest) GetStrongScratches() bool {
	if x != nil {
		return x.StrongScratches
	}
	return false
}

func (x *InspectVehicleRequest) GetElectricFail() bool {
	if x != nil {
		return x.ElectricFail
	}
	return false
}

func (x *InspectVehicleRequest) GetSuspensionFail() bool {
	if x != nil {
		return x.SuspensionFail
	}
	return false
}

type InspectVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vin           string                 `protobuf:"bytes,1,opt,name=vin,proto3" json:"vin,omitempty"`
	Grade         int32                  `protobuf:"varint,2,opt,name=grade,proto3" json:"grade,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InspectVehicleResponse) Reset() {
	*x = InspectVehicleResponse{}
	mi := &file_inspection_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InspectVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InspectVehicleResponse) ProtoMessage() {}

func (x *InspectVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_inspection_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InspectVehicleResponse.ProtoReflect.Descriptor instead.
func (*InspectVehicleResponse) Descriptor() ([]byte, []int) {
	return file_inspection_proto_rawDescGZIP(), []int{3}
}

func (x *InspectVehicleResponse) GetVin() string {
	if x != nil {
		return x.Vin
	}
	return ""
}

func (x *InspectVehicleResponse) GetGrade() int32 {
	if x != nil {
		return x.Grade
	}
	return 0
}

var File_inspection_proto protoreflect.FileDescriptor

const file_inspection_proto_rawDesc = "" +
	"\n" +
	"\x10inspection.proto\x12\n" +
	"inspection\x1a\x1cgoogle/api/annotations.proto\"'\n" +
	"\x13GetBuildDataRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\"\x8b\x01\n" +
	"\x11BuildDataResponse\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x14\n" +
	"\x05brand\x18\x02 \x01(\tR\x05brand\x12\x16\n" +
	"\x06engine\x18\x03 \x01(\tR\x06engine\x12\"\n" +
	"\ftransmission\x18\x04 \x01(\tR\ftransmission\x12\x12\n" +
	"\x04msrp\x18\x05 \x01(\x04R\x04msrp\"\xfb\x01\n" +
	"\x15InspectVehicleRequest\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x12\n" +
	"\x04year\x18\x02 \x01(\x05R\x04year\x12\x1a\n" +
	"\bodometer\x18\x03 \x01(\x05R\bodometer\x12'\n" +
	"\x0fsmall_scratches\x18\x04 \x01(\bR\x0esmallScratches\x12)\n" +
	"\x10strong_scratches\x18\x05 \x01(\bR\x0fstrongScratches\x12#\n" +
	"\relectric_fail\x18\x06 \x01(\bR\felectricFail\x12'\n" +
	"\x0fsuspension_fail\x18\a \x01(\bR\x0esuspensionFail\"@\n" +
	"\x16InspectVehicleResponse\x12\x10\n" +
	"\x03vin\x18\x01 \x01(\tR\x03vin\x12\x14\n" +
	"\x05grade\x18\x02 \x01(\x05R\x05grade2\x86\x02\n" +
	"\x11InspectionService\x12x\n" +
	"\fGetBuildData\x12\x1f.inspection.GetBuildDataRequest\x1a\x1d.inspection.BuildDataResponse\"(\x82\xd3\xe4\x93\x02\"\x12 /inspection/get-build-data/{vin}\x12w\n" +
	"\x0eInspectVehicle\x12!.inspection.InspectVehicleRequest\x1a\".inspection.InspectVehicleResponse\"\x1e\x82\xd3\xe4\x93\x02\x18:\x01*\"\x13/inspection/inspectBmZkgithub.com/alechekz/online-car-auction-clean-archv2/services/inspection/internal/transport/gRPC/proto;protob\x06proto3"

var (
	file_inspection_proto_rawDescOnce sync.Once
	file_inspection_proto_rawDescData []byte
)

func file_inspection_proto_rawDescGZIP() []byte {
	file_inspection_proto_rawDescOnce.Do(func() {
		file_inspection_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_inspection_proto_rawDesc), len(file_inspection_proto_rawDesc)))
	})
	return file_inspection_proto_rawDescData
}

var file_inspection_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_inspection_proto_goTypes = []any{
	(*GetBuildDataRequest)(nil),    // 0: inspection.GetBuildDataRequest
	(*BuildDataResponse)(nil),      // 1: inspection.BuildDataResponse
	(*InspectVehicleRequest)(nil),  // 2: inspection.InspectVehicleRequest
	(*InspectVehicleResponse)(nil), // 3: inspection.InspectVehicleResponse
}
var file_inspection_proto_depIdxs = []int32{
	0, // 0: inspection.InspectionService.GetBuildData:input_type -> inspection.GetBuildDataRequest
	2, // 1: inspection.InspectionService.InspectVehicle:input_type -> inspection.InspectVehicleRequest
	1, // 2: inspection.InspectionService.GetBuildData:output_type -> inspection.BuildDataResponse
	3, // 3: inspection.InspectionService.InspectVehicle:output_type -> inspection.InspectVehicleResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_inspection_proto_init() }
func file_inspection_proto_init() {
	if File_inspection_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_inspection_proto_rawDesc), len(file_inspection_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_inspection_proto_goTypes,
		DependencyIndexes: file_inspection_proto_depIdxs,
		MessageInfos:      file_inspection_proto_msgTypes,
	}.Build()
	File_inspection_proto = out.File
	file_inspection_proto_goTypes = nil
	file_inspection_proto_depIdxs = nil
}
